; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = prod

[env]
platform = https://github.com/tasmota/platform-espressif32/releases/download/2023.07.00/platform-espressif32.zip
board = esp32dev
framework = arduino
build_unflags = -fno-lto
lib_deps = 
	bblanchon/ArduinoJson@6.21.3
	rlogiacco/CircularBuffer@1.4.0
	sstaub/Ticker@4.4.0
	Martin-Laclaustra/CronAlarms@0.1.0
	marvinroger/AsyncMqttClient@0.9.0
	me-no-dev/AsyncTCP@1.1.1
	milesburton/DallasTemperature@3.11.0
monitor_filters = direct 
monitor_speed = 115200
upload_speed = 460800
extra_scripts = 
	pre:tools/backhaul/prepare-web-server.py
	pre:tools/build/pre_build.py
	pre:tools/webfilesbuilder/build_html.py
	pre:tools/export_compile_commands.py
	post:tools/build/build.py
build_flags = 
	-DBUILD_ENV_NAME=$PIOENV
	-flto

[env:prod]
build_flags = 
	${env.build_flags}
extra_scripts = 
	${env.extra_scripts}


[env:debug]
build_flags = 
	-DDEBUG
	${env.build_flags}
extra_scripts = 
	${env.extra_scripts}
lib_deps = 
	${env.lib_deps}
