#!/usr/bin/env python3
"""Generate one standalone Python script, including the Docker worker source."""
from pathlib import Path
import ast

root = Path(__file__).resolve().parents[2]
client = (root/'tools/backhaul/czc_pair.py').read_text()
# Only transport/AF helpers. Exclude provisioning, OTA, NV, and file-report commands.
client = client.split('\ndef acceptance(args, key):')[0]
radio = client + '\n' + (root/'tools/backhaul/accept_hardware_radio.py').read_text()
host = (root/'tools/backhaul/accept_hardware.py').read_text()
assert "'''" not in radio
body = "RADIO_SOURCE = r'''" + radio + "'''\n" + host
ast.parse(body)
output = root/'.backhaul-tests/czc-two-device-acceptance.py'
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text('''#!/usr/bin/env python3
# Самостоятельный скрипт: перенесите этот файл на машину с доступом к CZC.
# Справка: python3 czc-two-device-acceptance.py --help
# Нужны Python 3.9+ и Docker; Z2M и Mosquitto могут быть остановлены.
# Generated by tools/backhaul/make_acceptance_script.py; edit source files there.
''' + body)
print(str(output))
