#!/usr/bin/env python3
"""Generate TLS build inputs and check the Mbed TLS dependency."""
import argparse
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[2]
VERSION = '3.6.7'
COMMIT = '068ff080b369adfac81509f9b57b2afabaf82dc5'
URL = 'https://github.com/Mbed-TLS/mbedtls.git'
OUT = ROOT / 'lib/CzcPeerTls'
SOURCE = OUT / 'mbedtls'


def git(*args):
    return subprocess.check_output(['git', '-C', str(SOURCE), *args], text=True).strip()


def verify_upstream():
    if not (SOURCE / '.git').exists():
        raise SystemExit('Initialize Mbed TLS: git submodule update --init --recursive')
    if git('rev-parse', 'HEAD') != COMMIT:
        raise SystemExit(f'Mbed TLS submodule must be at release {VERSION} ({COMMIT})')
    changed = git('diff', '--name-only', 'HEAD', '--', 'include', 'library', 'LICENSE')
    if changed:
        raise SystemExit('Mbed TLS upstream files were modified:\n' + changed)
    extra = git('ls-files', '--others', '--exclude-standard', '--', 'include', 'library')
    if extra:
        raise SystemExit('Unexpected Mbed TLS build inputs:\n' + extra)


def contents():
    if not (SOURCE / 'include/mbedtls/version.h').is_file():
        raise SystemExit('Initialize Mbed TLS: git submodule update --init --recursive')
    files = {'LICENSE': (SOURCE / 'LICENSE').read_bytes()}
    for directory in ('include/mbedtls', 'include/psa', 'library'):
        for path in sorted((SOURCE / directory).rglob('*')):
            if path.is_file() and (directory != 'library' or path.suffix in ('.c', '.h')):
                files[path.relative_to(SOURCE).as_posix()] = path.read_bytes()
    return files


def generated(files, debug=False):
    # These macros are private to this library's C translation units. SDK TLS
    # and the C++ application see only the opaque CzcPeerTls.h interface.
    identifiers, macros = set(), set()
    for name, data in files.items():
        if name == 'LICENSE':
            continue
        text = data.decode()
        identifiers.update(re.findall(r'\b(?:mbedtls|psa)_[A-Za-z0-9_]+\b', text))
        macros.update(re.findall(r'^\s*#\s*define\s+((?:mbedtls|psa)_\w+)', text, re.M))
    prefix = ['// Generated by prepare-peer-tls.py.', '#pragma once']
    for name in sorted(identifiers - macros):
        if name in ('psa_import_key', 'psa_destroy_key'):
            prefix += ['#ifdef CZC_TLS_ENGINE_PROFILE', f'#define {name} czc_tls_guard_{name}',
                       '#else', f'#define {name} czc_tls3_{name}', '#endif']
        elif name.startswith('mbedtls_ssl_'):
            prefix += ['#ifdef CZC_TLS_ADMIN', f'#define {name} czc_admin3_{name}',
                       '#else', f'#define {name} czc_peer3_{name}', '#endif']
        else:
            prefix.append(f'#define {name} czc_tls3_{name}')
    result = {'CzcTlsSymbols.h': ('\n'.join(prefix) + '\n').encode()}
    # Both TLS profiles use one shared crypto implementation. The admin server
    # accepts standard 16 KiB input; peers negotiate a 1 KiB record size limit.
    for name in sorted(files):
        path = Path(name)
        if path.parent.as_posix() != 'library' or path.suffix != '.c':
            continue
        profiles = (('peer', 'admin') if debug else ('peer',)) if path.name.startswith('ssl_') else ('crypto',)
        for profile in profiles:
            if profile == 'admin' and path.name in ('ssl_tls12_client.c', 'ssl_tls13_client.c'):
                continue
            wrapper = '// Generated by prepare-peer-tls.py.\n'
            if profile == 'admin':
                wrapper += '#define CZC_TLS_ADMIN\n'
            if profile in ('peer', 'admin'):
                wrapper += '#define CZC_TLS_ENGINE_PROFILE\n'
            wrapper += '#include "CzcTlsConfig.h"\n'
            wrapper += f'#include "{name}"\n'
            result[f'{profile}/{path.name}'] = wrapper.encode()
    result['peer/engine.c'] = b'#define CZC_TLS_ENGINE_PROFILE\n#include "CzcTlsEngine.inc"\n'
    if debug:
        result['admin/engine.c'] = b'#define CZC_TLS_ADMIN\n#define CZC_TLS_ENGINE_PROFILE\n#include "CzcTlsEngine.inc"\n'
    return result


def prepare(output, debug=False):
    output = Path(output).resolve()
    if output == OUT or OUT in output.parents:
        raise ValueError('Generated TLS inputs belong in a build directory outside lib/CzcPeerTls')
    expected = generated(contents(), debug)
    for directory in ('peer', 'admin', 'crypto'):
        for path in (output / directory).glob('*.c'):
            if path.relative_to(output).as_posix() not in expected:
                path.unlink()
    for name, data in expected.items():
        path = output / name
        if path.is_file() and path.read_bytes() == data:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(path.suffix + '.tmp')
        temporary.write_bytes(data)
        temporary.replace(path)
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check the Mbed TLS dependency')
    parser.add_argument('--output', type=Path, help='Build directory for generated sources and symbol header')
    parser.add_argument('--debug', action='store_true', help='Include the administrative TLS profile')
    args = parser.parse_args()
    if args.check:
        verify_upstream()
        metadata = json.loads((OUT / 'upstream.json').read_text())
        if metadata['commit'] != COMMIT or metadata['version'] != VERSION or metadata['url'] != URL:
            raise SystemExit('Mbed TLS provenance metadata differs from the pinned dependency')
        if (OUT / 'LICENSE').read_bytes() != (SOURCE / 'LICENSE').read_bytes():
            raise SystemExit('Mbed TLS license differs from the pinned dependency')
        print(f'PASS Mbed TLS {VERSION} dependency check')
    if args.output:
        prepare(args.output, args.debug)
        print(f'Generated TLS build inputs: {args.output}')
    elif not args.check:
        parser.error('provide --output BUILD_DIRECTORY or --check')


if __name__ == '__main__':
    main()
